create database customer_behavior;
-- viewing the whole table
select * from customer_trend;

-- Total revenue generated by Male vs female customers
select gender,sum(purchase_amount) as revenue_by_gender 
from customer_trend
group by 1;

-- Which customer used a discount but still spent more than average amount






